// web/src/app/cluster/cluster-feature.tsx
import { useState } from 'react'
import { AppHero } from '../ui/ui-layout'
import { ClusterUiModal } from './cluster-ui'
import { ClusterUiTable } from './cluster-ui'

export default function ClusterFeature() {
  const [showModal, setShowModal] = useState(false)

  return (
    <div>
      <AppHero title="Clusters" subtitle="Manage and select your Solana clusters">
        <ClusterUiModal show={showModal} hideModal={() => setShowModal(false)} />
        <button className="btn btn-xs lg:btn-md btn-primary" onClick={() => setShowModal(true)}>
          Add Cluster
        </button>
      </AppHero>
      <ClusterUiTable />
    </div>
  )
}

// demo/src/app/cluster/cluster-feature.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { AppHeroComponent, AppTableComponent } from '../ui/ui-layout.component';

@Component({
  selector: 'dapp-cluster-feature',
  standalone: true,
  imports: [CommonModule, AppHeroComponent, AppTableComponent],
  template: `<div>
    <dapp-app-hero
      title="Clusters"
      subtitle="Manage and select your Solana clusters"
    >
      <!--      <dapp-app-modal />-->
      <button class="btn btn-xs lg:btn-md btn-primary">Add Cluster</button>
    </dapp-app-hero>
    <!--    <ClusterUiTable />-->
    <dapp-app-table />
  </div>`,
  styles: ``,
})
export class ClusterFeatureComponent {}
