// web/src/app/account/account-ui.tsx
import { useWallet } from '@solana/wallet-adapter-react'
import { LAMPORTS_PER_SOL, PublicKey } from '@solana/web3.js'
import { IconRefresh } from '@tabler/icons-react'
import { useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { AppModal, ellipsify } from '../ui/ui-layout'
import { useCluster } from '../cluster/cluster-data-access'
import { ExplorerLink } from '../cluster/cluster-ui'
import {
  useGetBalance,
  useGetSignatures,
  useGetTokenAccounts,
  useRequestAirdrop,
  useTransferSol,
} from './account-data-access'

export function AccountBalance({ address }: { address: PublicKey }) {
  const query = useGetBalance({ address })

  return (
    <div>
      <h1 className="text-5xl font-bold cursor-pointer" onClick={() => query.refetch()}>
        {query.data ? <BalanceSol balance={query.data} /> : '...'} SOL
      </h1>
    </div>
  )
}
export function AccountChecker() {
  const { publicKey } = useWallet()
  if (!publicKey) {
    return null
  }
  return <AccountBalanceCheck address={publicKey} />
}
export function AccountBalanceCheck({ address }: { address: PublicKey }) {
  const { cluster } = useCluster()
  const mutation = useRequestAirdrop({ address })
  const query = useGetBalance({ address })

  if (query.isLoading) {
    return null
  }
  if (query.isError || !query.data) {
    return (
      <div className="alert alert-warning text-warning-content/80 rounded-none flex justify-center">
        <span>
          You are connected to <strong>{cluster.name}</strong> but your account is not found on this cluster.
        </span>
        <button
          className="btn btn-xs btn-neutral"
          onClick={() => mutation.mutateAsync(1).catch((err) => console.log(err))}
        >
          Request Airdrop
        </button>
      </div>
    )
  }
  return null
}

export function AccountButtons({ address }: { address: PublicKey }) {
  const wallet = useWallet()
  const { cluster } = useCluster()
  const [showAirdropModal, setShowAirdropModal] = useState(false)
  const [showReceiveModal, setShowReceiveModal] = useState(false)
  const [showSendModal, setShowSendModal] = useState(false)

  return (
    <div>
      <ModalAirdrop hide={() => setShowAirdropModal(false)} address={address} show={showAirdropModal} />
      <ModalReceive address={address} show={showReceiveModal} hide={() => setShowReceiveModal(false)} />
      <ModalSend address={address} show={showSendModal} hide={() => setShowSendModal(false)} />
      <div className="space-x-2">
        <button
          disabled={cluster.network?.includes('mainnet')}
          className="btn btn-xs lg:btn-md btn-outline"
          onClick={() => setShowAirdropModal(true)}
        >
          Airdrop
        </button>
        <button
          disabled={wallet.publicKey?.toString() !== address.toString()}
          className="btn btn-xs lg:btn-md btn-outline"
          onClick={() => setShowSendModal(true)}
        >
          Send
        </button>
        <button className="btn btn-xs lg:btn-md btn-outline" onClick={() => setShowReceiveModal(true)}>
          Receive
        </button>
      </div>
    </div>
  )
}

export function AccountTokens({ address }: { address: PublicKey }) {
  const [showAll, setShowAll] = useState(false)
  const query = useGetTokenAccounts({ address })
  const client = useQueryClient()
  const items = useMemo(() => {
    if (showAll) return query.data
    return query.data?.slice(0, 5)
  }, [query.data, showAll])

  return (
    <div className="space-y-2">
      <div className="justify-between">
        <div className="flex justify-between">
          <h2 className="text-2xl font-bold">Token Accounts</h2>
          <div className="space-x-2">
            {query.isLoading ? (
              <span className="loading loading-spinner"></span>
            ) : (
              <button
                className="btn btn-sm btn-outline"
                onClick={async () => {
                  await query.refetch()
                  await client.invalidateQueries({
                    queryKey: ['getTokenAccountBalance'],
                  })
                }}
              >
                <IconRefresh size={16} />
              </button>
            )}
          </div>
        </div>
      </div>
      {query.isError && <pre className="alert alert-error">Error: {query.error?.message.toString()}</pre>}
      {query.isSuccess && (
        <div>
          {query.data.length === 0 ? (
            <div>No token accounts found.</div>
          ) : (
            <table className="table border-4 rounded-lg border-separate border-base-300">
              <thead>
                <tr>
                  <th>Public Key</th>
                  <th>Mint</th>
                  <th className="text-right">Balance</th>
                </tr>
              </thead>
              <tbody>
                {items?.map(({ account, pubkey }) => (
                  <tr key={pubkey.toString()}>
                    <td>
                      <div className="flex space-x-2">
                        <span className="font-mono">
                          <ExplorerLink label={ellipsify(pubkey.toString())} path={`account/${pubkey.toString()}`} />
                        </span>
                      </div>
                    </td>
                    <td>
                      <div className="flex space-x-2">
                        <span className="font-mono">
                          <ExplorerLink
                            label={ellipsify(account.data.parsed.info.mint)}
                            path={`account/${account.data.parsed.info.mint.toString()}`}
                          />
                        </span>
                      </div>
                    </td>
                    <td className="text-right">
                      <span className="font-mono">{account.data.parsed.info.tokenAmount.uiAmount}</span>
                    </td>
                  </tr>
                ))}

                {(query.data?.length ?? 0) > 5 && (
                  <tr>
                    <td colSpan={4} className="text-center">
                      <button className="btn btn-xs btn-outline" onClick={() => setShowAll(!showAll)}>
                        {showAll ? 'Show Less' : 'Show All'}
                      </button>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  )
}

export function AccountTransactions({ address }: { address: PublicKey }) {
  const query = useGetSignatures({ address })
  const [showAll, setShowAll] = useState(false)

  const items = useMemo(() => {
    if (showAll) return query.data
    return query.data?.slice(0, 5)
  }, [query.data, showAll])

  return (
    <div className="space-y-2">
      <div className="flex justify-between">
        <h2 className="text-2xl font-bold">Transaction History</h2>
        <div className="space-x-2">
          {query.isLoading ? (
            <span className="loading loading-spinner"></span>
          ) : (
            <button className="btn btn-sm btn-outline" onClick={() => query.refetch()}>
              <IconRefresh size={16} />
            </button>
          )}
        </div>
      </div>
      {query.isError && <pre className="alert alert-error">Error: {query.error?.message.toString()}</pre>}
      {query.isSuccess && (
        <div>
          {query.data.length === 0 ? (
            <div>No transactions found.</div>
          ) : (
            <table className="table border-4 rounded-lg border-separate border-base-300">
              <thead>
                <tr>
                  <th>Signature</th>
                  <th className="text-right">Slot</th>
                  <th>Block Time</th>
                  <th className="text-right">Status</th>
                </tr>
              </thead>
              <tbody>
                {items?.map((item) => (
                  <tr key={item.signature}>
                    <th className="font-mono">
                      <ExplorerLink path={`tx/${item.signature}`} label={ellipsify(item.signature, 8)} />
                    </th>
                    <td className="font-mono text-right">
                      <ExplorerLink path={`block/${item.slot}`} label={item.slot.toString()} />
                    </td>
                    <td>{new Date((item.blockTime ?? 0) * 1000).toISOString()}</td>
                    <td className="text-right">
                      {item.err ? (
                        <div className="badge badge-error" title={JSON.stringify(item.err)}>
                          Failed
                        </div>
                      ) : (
                        <div className="badge badge-success">Success</div>
                      )}
                    </td>
                  </tr>
                ))}
                {(query.data?.length ?? 0) > 5 && (
                  <tr>
                    <td colSpan={4} className="text-center">
                      <button className="btn btn-xs btn-outline" onClick={() => setShowAll(!showAll)}>
                        {showAll ? 'Show Less' : 'Show All'}
                      </button>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  )
}

function BalanceSol({ balance }: { balance: number }) {
  return <span>{Math.round((balance / LAMPORTS_PER_SOL) * 100000) / 100000}</span>
}

function ModalReceive({ hide, show, address }: { hide: () => void; show: boolean; address: PublicKey }) {
  return (
    <AppModal title="Receive" hide={hide} show={show}>
      <p>Receive assets by sending them to your public key:</p>
      <code>{address.toString()}</code>
    </AppModal>
  )
}

function ModalAirdrop({ hide, show, address }: { hide: () => void; show: boolean; address: PublicKey }) {
  const mutation = useRequestAirdrop({ address })
  const [amount, setAmount] = useState('2')

  return (
    <AppModal
      hide={hide}
      show={show}
      title="Airdrop"
      submitDisabled={!amount || mutation.isPending}
      submitLabel="Request Airdrop"
      submit={() => mutation.mutateAsync(parseFloat(amount)).then(() => hide())}
    >
      <input
        disabled={mutation.isPending}
        type="number"
        step="any"
        min="1"
        placeholder="Amount"
        className="input input-bordered w-full"
        value={amount}
        onChange={(e) => setAmount(e.target.value)}
      />
    </AppModal>
  )
}

function ModalSend({ hide, show, address }: { hide: () => void; show: boolean; address: PublicKey }) {
  const wallet = useWallet()
  const mutation = useTransferSol({ address })
  const [destination, setDestination] = useState('')
  const [amount, setAmount] = useState('1')

  if (!address || !wallet.sendTransaction) {
    return <div>Wallet not connected</div>
  }

  return (
    <AppModal
      hide={hide}
      show={show}
      title="Send"
      submitDisabled={!destination || !amount || mutation.isPending}
      submitLabel="Send"
      submit={() => {
        mutation
          .mutateAsync({
            destination: new PublicKey(destination),
            amount: parseFloat(amount),
          })
          .then(() => hide())
      }}
    >
      <input
        disabled={mutation.isPending}
        type="text"
        placeholder="Destination"
        className="input input-bordered w-full"
        value={destination}
        onChange={(e) => setDestination(e.target.value)}
      />
      <input
        disabled={mutation.isPending}
        type="number"
        step="any"
        min="1"
        placeholder="Amount"
        className="input input-bordered w-full"
        value={amount}
        onChange={(e) => setAmount(e.target.value)}
      />
    </AppModal>
  )
}

// demo/src/app/account/account-ui.component.ts
import { CommonModule, JsonPipe } from '@angular/common';
import { Component, inject, Inject, input, Input } from '@angular/core';
import { AccountService, Transaction } from './account-data-access.component';
import { Dialog, DIALOG_DATA } from '@angular/cdk/dialog';
import { AppModalComponent } from '../ui/ui-layout.component';
import { MatIconModule } from '@angular/material/icon';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { computedAsync } from 'ngxtension/computed-async';
import { LAMPORTS_PER_SOL, PublicKey } from '@solana/web3.js';
import { TOKEN_PROGRAM_ID } from '@solana/spl-token';

@Component({
  selector: 'dapp-balance-sol',
  standalone: true,
  imports: [CommonModule],
  template: `<span>{{ converted }}</span>`,
})
export class BalanceSolComponent {
  @Input() balance!: number | null | undefined;

  get converted() {
    return (
      Math.round(((this.balance ?? 0) / LAMPORTS_PER_SOL) * 100000) / 100000
    );
  }
}

@Component({
  selector: 'dapp-account-balance',
  standalone: true,
  imports: [CommonModule, BalanceSolComponent],
  template: `
    <div>
      <h1 class="text-5xl font-bold cursor-pointer">
        @if (balance()) {
        <dapp-balance-sol [balance]="balance()" />
        SOL }
      </h1>
    </div>
  `,
})
export class AccountBalanceComponent {
  // @Input() address!: string;
  readonly address = input.required<string>();
  private readonly _accountService = inject(AccountService);

  readonly balance = computedAsync(
    () => this._accountService.getBalance(this.address()),
    { requireSync: false }
  );
}

@Component({
  template: ` <p>ModalAirdropDialogComponent: {{ data.message }}</p> `,
  standalone: true,
  styles: [
    `
      :host {
        display: block;
        background: #fff;
        border-radius: 8px;
        padding: 8px 16px;
      }
    `,
  ],
})
export class ModalAirdropDialogComponent {
  constructor(@Inject(DIALOG_DATA) public data: { message: string }) {}
}

@Component({
  selector: 'dapp-modal-airdrop',
  standalone: true,
  imports: [CommonModule, AppModalComponent, ReactiveFormsModule],
  template: `
    <form [formGroup]="form" (ngSubmit)="doSubmit()">
      <dapp-app-modal
        [submitDisabled]="false"
        (doSubmit)="doSubmit()"
        title="Airdrop"
        submitLabel="Request Airdrop"
      >
        <input
          type="number"
          step="any"
          min="1"
          placeholder="Amount"
          class="input input-bordered w-full"
          formControlName="number"
        />
      </dapp-app-modal>
    </form>
  `,
})
export class ModalAirdropComponent {
  form: FormGroup;
  constructor() {
    this.form = new FormGroup({
      number: new FormControl(''),
    });
  }

  doSubmit() {
    console.log(this.form.value);
  }
}

@Component({
  selector: 'dapp-modal-send',
  standalone: true,
  imports: [CommonModule, AppModalComponent, ReactiveFormsModule],
  template: `
    <form [formGroup]="form" (ngSubmit)="doSubmit()">
      <dapp-app-modal
        [submitDisabled]="false"
        (doSubmit)="doSubmit()"
        title="Send"
        submitLabel="Send"
      >
        <input
          type="text"
          placeholder="Destination"
          class="input input-bordered w-full"
          formControlName="destination"
        />
        <input
          type="number"
          step="any"
          min="1"
          placeholder="Amount"
          class="input input-bordered w-full"
          formControlName="amount"
        />
      </dapp-app-modal>
    </form>
  `,
  styles: ``,
})
export class ModalSendComponent {
  form: FormGroup;
  constructor() {
    this.form = new FormGroup({
      destination: new FormControl(''),
      amount: new FormControl(''),
    });
  }

  doSubmit() {
    console.log(this.form.value);
  }
}

@Component({
  selector: 'dapp-modal-receive',
  standalone: true,
  imports: [CommonModule, AppModalComponent],
  template: `
    <dapp-app-modal
      [submitDisabled]="false"
      title="Receive"
      submitLabel="Receive"
    >
      <p>Receive assets by sending them to your public key:</p>
      <code> CvQf1w1T828bRqfD6fA1rWdCR4ybCsEr6vwHdYPTMfSr</code>
    </dapp-app-modal>
  `,
  styles: ``,
})
export class ModalReceiveComponent {
  constructor(public dialog: Dialog) {}

  showModal() {
    this.dialog.open(AppModalComponent, {
      minWidth: '300px',
      data: {
        button: 'Close',
      },
    });
  }
}
@Component({
  selector: 'dapp-account-buttons',
  standalone: true,
  imports: [
    CommonModule,
    ModalAirdropComponent,
    ModalSendComponent,
    ModalReceiveComponent,
  ],
  template: `
    <div class="space-x-2">
      <button (click)="showAirdrop()" class="btn btn-xs lg:btn-md btn-outline">
        Airdrop
      </button>
      <button (click)="showSend()" class="btn btn-xs lg:btn-md btn-outline">
        Send</button
      ><button (click)="showReceive()" class="btn btn-xs lg:btn-md btn-outline">
        Receive
      </button>
    </div>
  `,
  styles: ``,
})
export class AccountButtonsComponent {
  private readonly dialog = inject(Dialog);
  showAirdrop() {
    this.dialog.open(ModalAirdropComponent);
  }
  showSend() {
    this.dialog.open(ModalSendComponent);
  }
  showReceive() {
    this.dialog.open(ModalReceiveComponent);
  }
}

@Component({
  selector: 'dapp-account-tokens',
  standalone: true,
  imports: [CommonModule, MatIconModule, JsonPipe],
  template: `
    <div class="space-y-2">
      <div class="justify-between">
        <div class="flex justify-between">
          <h2 class="text-2xl font-bold">Token Accounts</h2>
          <div class="space-x-2">
            <!--            <span class="loading loading-spinner"></span>-->

            <button class="btn btn-sm btn-outline" (click)="query.refetch()">
              <mat-icon
                aria-hidden="false"
                aria-label="refresh items"
                fontIcon="refresh"
              />
            </button>
          </div>
        </div>
      </div>
      <!--      <pre class="alert alert-error"></pre>-->

      <div>
        <!--        <div>No token accounts found.</div>-->
        <table
          class="table border-4 rounded-lg border-separate border-base-300"
        >
          <thead>
            <tr>
              <th>Public Key</th>
              <th>Mint</th>
              <th class="text-right">Balance</th>
            </tr>
          </thead>
          <tbody>
            @for(item of items(); track item){
            <tr>
              <td>
                <div class="flex space-x-2">
                  <span class="font-mono">
                    <a>{{ item.pubkey }}</a>
                  </span>
                </div>
              </td>
              <td>
                <div class="flex space-x-2">
                  <span class="font-mono">
                    <a>{{ item.account.data.parsed?.info.mint }}</a>
                  </span>
                </div>
              </td>
              <td class="text-right">
                <span class="font-mono">{{
                  item.account.data.parsed?.info?.tokenAmount?.uiAmount
                }}</span>
              </td>
            </tr>

            <tr>
              <td class="text-center">
                <!--                <button class="btn btn-xs btn-outline"></button>-->
              </td>
            </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `,
})
export class AccountTokensComponent {
  readonly address = input<string>();
  private readonly accountService = inject(AccountService);

  readonly query = this.accountService.getTokenAccounts(
    this.address()
      ? new PublicKey(this.address)
      : new PublicKey('CvQf1w1T828bRqfD6fA1rWdCR4ybCsEr6vwHdYPTMfSr')
  );

  showAll = false;
  setShowAll() {
    this.showAll = !this.showAll;
  }

  // readonly items = computed(() => this.query.data);
  readonly items = computedAsync(() => this.query.data(), {
    requireSync: false,
  });
}

@Component({
  selector: 'dapp-account-transactions',
  standalone: true,
  imports: [CommonModule, MatIconModule],
  template: ` <div class="space-y-2">
    <div class="flex justify-between">
      <h2 class="text-2xl font-bold">Transaction History</h2>
      <div class="space-x-2">
        <!--        <span class="loading loading-spinner"></span>-->
        <button class="btn btn-sm btn-outline">
          <mat-icon
            aria-hidden="false"
            aria-label="refresh items"
            fontIcon="refresh"
          />
        </button>
      </div>
    </div>
    <!--    <pre class="alert alert-error">Error: </pre>-->

    <div>
      <!--      <div>No transactions found.</div>-->

      <table class="table border-4 rounded-lg border-separate border-base-300">
        <thead>
          <tr>
            <th>Signature</th>
            <th class="text-right">Slot</th>
            <th>Block Time</th>
            <th class="text-right">Status</th>
          </tr>
        </thead>
        <tbody>
          @for(transaction of transactions; track transaction){
          <tr>
            <th class="font-mono">
              <a>{{ transaction.signature }}</a>
            </th>
            <td class="font-mono text-right">
              <a>{{ transaction.slot }}</a>
            </td>
            <td>{{ transaction.blockTime }}</td>
            <td class="text-right">
              <!--              <div class="badge badge-error">Failed</div>-->

              <div class="badge badge-success">{{ transaction.status }}</div>
            </td>
          </tr>

          }
        </tbody>
        <tr>
          <td colSpan="{4}" class="text-center">
            <button class="btn btn-xs btn-outline">Show All</button>
          </td>
        </tr>
      </table>
    </div>
  </div>`,
  styles: ``,
})
export class AccountTransactionsComponent {
  @Input() transactions: Transaction[] = [];
}
