// demo/src/app/counter/counter-feature.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { AppHeroComponent } from '../ui/ui-layout.component';
import {
  CounterCardComponent,
  CounterCreateComponent,
} from './counter-ui.component';
import { Counter, defaultCounters } from './counter-data-access.component';

@Component({
  selector: 'dapp-counter-feature',
  standalone: true,
  imports: [
    CommonModule,
    AppHeroComponent,
    CounterCreateComponent,
    CounterCardComponent,
  ],
  template: `
    <div>
      <dapp-app-hero>
        <h1>Counter</h1>
        <h3>
          Create a new account by clicking the "Create" button. The state of a
          account is stored on-chain and can be manipulated by calling the
          program's methods (increment, decrement, set, and close).
        </h3>
        <p class="mb-6">
          <a>Id wallet</a>
        </p>
        <dapp-counter-create />
      </dapp-app-hero>
      <dapp-counter-card [counters]="defaultCounters" />
    </div>
    <div class="max-w-4xl mx-auto">
      <div class="hero py-[64px]">
        <div class="hero-content text-center">wallet</div>
      </div>
    </div>
  `,
})
export class CounterFeatureComponent {
  defaultCounters: Counter[] = defaultCounters;
}

// web/src/app/counter/counter-feature.tsx
import { useWallet } from '@solana/wallet-adapter-react'
import { WalletButton } from '../solana/solana-provider'
import { AppHero, ellipsify } from '../ui/ui-layout'
import { ExplorerLink } from '../cluster/cluster-ui'
import { useCounterProgram } from './counter-data-access'
import { CounterCreate, CounterList } from './counter-ui'

export default function CounterFeature() {
  const { publicKey } = useWallet()
  const { programId } = useCounterProgram()

  return publicKey ? (
    <div>
      <AppHero
        title="Counter"
        subtitle={
          'Create a new account by clicking the "Create" button. The state of a account is stored on-chain and can be manipulated by calling the program\'s methods (increment, decrement, set, and close).'
        }
      >
        <p className="mb-6">
          <ExplorerLink path={`account/${programId}`} label={ellipsify(programId.toString())} />
        </p>
        <CounterCreate />
      </AppHero>
      <CounterList />
    </div>
  ) : (
    <div className="max-w-4xl mx-auto">
      <div className="hero py-[64px]">
        <div className="hero-content text-center">
          <WalletButton />
        </div>
      </div>
    </div>
  )
}
