// demo/src/app/counter/counter-ui.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Counter } from './counter-data-access.component';

@Component({
  selector: 'dapp-counter-ui',
  standalone: true,
  imports: [CommonModule],
  template: `<p>counter-ui works!</p>`,
})
export class CounterUiComponent {}

@Component({
  selector: 'dapp-counter-create',
  standalone: true,
  imports: [CommonModule],
  template: `<button class="btn btn-xs lg:btn-md btn-primary">Create</button>`,
})
export class CounterCreateComponent {}

@Component({
  selector: 'dapp-counter-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    @for(counter of counters; track counter){
    <div
      class="card card-bordered border-base-300 border-4 text-neutral-content"
    >
      <div class="card-body items-center text-center">
        <div class="space-y-6">
          <h2 class="card-title justify-center text-3xl cursor-pointer">
            {{ counter.count }}
          </h2>
          <div class="card-actions justify-around">
            <button class="btn btn-xs lg:btn-md btn-outline">
              {{ counter.increment }}
            </button>
            <button class="btn btn-xs lg:btn-md btn-outline">Set</button>
            <button class="btn btn-xs lg:btn-md btn-outline">Decrement</button>
          </div>
          <div class="text-center space-y-4">
            <p>
              <a>Account</a>
            </p>
            <button class="btn btn-xs btn-secondary btn-outline">Close</button>
          </div>
        </div>
      </div>
    </div>
    }
  `,
})
export class CounterCardComponent {
  @Input() counters: Counter[] = [];
}

// web/src/app/counter/counter-ui.tsx
import { Keypair, PublicKey } from '@solana/web3.js'
import { useMemo } from 'react'
import { ellipsify } from '../ui/ui-layout'
import { ExplorerLink } from '../cluster/cluster-ui'
import { useCounterProgram, useCounterProgramAccount } from './counter-data-access'

export function CounterCreate() {
  const { initialize } = useCounterProgram()

  return (
    <button
      className="btn btn-xs lg:btn-md btn-primary"
      onClick={() => initialize.mutateAsync(Keypair.generate())}
      disabled={initialize.isPending}
    >
      Create {initialize.isPending && '...'}
    </button>
  )
}

export function CounterList() {
  const { accounts, getProgramAccount } = useCounterProgram()

  if (getProgramAccount.isLoading) {
    return <span className="loading loading-spinner loading-lg"></span>
  }
  if (!getProgramAccount.data?.value) {
    return (
      <div className="alert alert-info flex justify-center">
        <span>Program account not found. Make sure you have deployed the program and are on the correct cluster.</span>
      </div>
    )
  }
  return (
    <div className={'space-y-6'}>
      {accounts.isLoading ? (
        <span className="loading loading-spinner loading-lg"></span>
      ) : accounts.data?.length ? (
        <div className="grid md:grid-cols-2 gap-4">
          {accounts.data?.map((account) => (
            <CounterCard key={account.publicKey.toString()} account={account.publicKey} />
          ))}
        </div>
      ) : (
        <div className="text-center">
          <h2 className={'text-2xl'}>No accounts</h2>
          No accounts found. Create one above to get started.
        </div>
      )}
    </div>
  )
}

function CounterCard({ account }: { account: PublicKey }) {
  const { accountQuery, incrementMutation, setMutation, decrementMutation, closeMutation } = useCounterProgramAccount({
    account,
  })

  const count = useMemo(() => accountQuery.data?.count ?? 0, [accountQuery.data?.count])

  return accountQuery.isLoading ? (
    <span className="loading loading-spinner loading-lg"></span>
  ) : (
    <div className="card card-bordered border-base-300 border-4 text-neutral-content">
      <div className="card-body items-center text-center">
        <div className="space-y-6">
          <h2 className="card-title justify-center text-3xl cursor-pointer" onClick={() => accountQuery.refetch()}>
            {count}
          </h2>
          <div className="card-actions justify-around">
            <button
              className="btn btn-xs lg:btn-md btn-outline"
              onClick={() => incrementMutation.mutateAsync()}
              disabled={incrementMutation.isPending}
            >
              Increment
            </button>
            <button
              className="btn btn-xs lg:btn-md btn-outline"
              onClick={() => {
                const value = window.prompt('Set value to:', count.toString() ?? '0')
                if (!value || parseInt(value) === count || isNaN(parseInt(value))) {
                  return
                }
                return setMutation.mutateAsync(parseInt(value))
              }}
              disabled={setMutation.isPending}
            >
              Set
            </button>
            <button
              className="btn btn-xs lg:btn-md btn-outline"
              onClick={() => decrementMutation.mutateAsync()}
              disabled={decrementMutation.isPending}
            >
              Decrement
            </button>
          </div>
          <div className="text-center space-y-4">
            <p>
              <ExplorerLink path={`account/${account}`} label={ellipsify(account.toString())} />
            </p>
            <button
              className="btn btn-xs btn-secondary btn-outline"
              onClick={() => {
                if (!window.confirm('Are you sure you want to close this account?')) {
                  return
                }
                return closeMutation.mutateAsync()
              }}
              disabled={closeMutation.isPending}
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
