// demo/src/app/ui/ui-layout.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'dapp-ui-layout',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterOutlet],
  template: `
    <div class="h-full flex flex-col">
      <div
        class="navbar bg-base-300 text-neutral-content flex-col md:flex-row space-y-2 md:space-y-0"
      >
        <div class="flex-1">
          <a class="btn btn-ghost normal-case text-xl" routerLink="/">
            <img
              class="h-4 md:h-6"
              alt="Solana Logo"
              src="/assets/solana-logo.png"
            />
          </a>
          @for (link of links; track link) {
          <a
            class="menu menu-horizontal px-1 space-x-2"
            [routerLink]="link.path"
            >{{ link.label }}</a
          >
          }
        </div>
        <div class="flex-none space-x-2">
          <button>wallet</button>
          <button>Devnet</button>
        </div>
      </div>
      <!--      <ClusterChecker>-->
      <!--        <AccountChecker />-->
      <!--      </ClusterChecker>-->

      <main class="flex-grow mx-4 lg:mx-auto">
        <router-outlet />
      </main>

      <footer class="footer footer-center p-4 bg-base-300 text-base-content">
        <aside>
          <p>
            Generated by
            <a
              class="link hover:text-white"
              href="https://github.com/solana-developers/create-solana-dapp"
              target="_blank"
              rel="noopener noreferrer"
            >
              create-solana-dapp
            </a>
          </p>
        </aside>
      </footer>
    </div>
  `,
  styles: ``,
})
export class UiLayoutComponent {
  @Input() links!: { label: string; path: string }[];
}

@Component({
  selector: 'dapp-app-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <dialog class="modal" open>
      <div class="modal-box space-y-5">
        <h3 class="font-bold text-lg">{{ title }}</h3>
        <ng-content />
        <div class="modal-action">
          <div class="join space-x-2">
            <button
              [disabled]="submitDisabled"
              class="btn btn-xs lg:btn-md btn-primary"
              (click)="doSubmit.emit()"
            >
              {{ submitLabel }}
            </button>
            <button class="btn">Close</button>
          </div>
        </div>
      </div>
    </dialog>
  `,
})
export class AppModalComponent {
  @Input() title!: string;
  @Input() submitLabel!: string;
  @Input() submitDisabled?: boolean;
  @Output() doSubmit = new EventEmitter();
}

@Component({
  selector: 'dapp-app-hero',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="hero py-[64px]">
      <div class="hero-content text-center">
        <div class="max-w-2xl">
          @if (title) {
          <h1 class="text-5xl font-bold">{{ title }}</h1>
          } @if (subtitle) {
          <p class="py-6">{{ subtitle }}</p>
          }
          <ng-content />
        </div>
      </div>
    </div>
  `,
  styles: ``,
})
export class AppHeroComponent {
  @Input() title?: string;
  @Input() subtitle?: string;
}

// web/src/app/ui/ui-layout.tsx
import { WalletButton } from '../solana/solana-provider'
import * as React from 'react'
import { ReactNode, Suspense, useEffect, useRef } from 'react'

import { Link, useLocation } from 'react-router-dom'

import { AccountChecker } from '../account/account-ui'
import { ClusterChecker, ClusterUiSelect, ExplorerLink } from '../cluster/cluster-ui'
import toast, { Toaster } from 'react-hot-toast'

export function UiLayout({ children, links }: { children: ReactNode; links: { label: string; path: string }[] }) {
  const { pathname } = useLocation()

  return (
    <div className="h-full flex flex-col">
      <div className="navbar bg-base-300 text-neutral-content flex-col md:flex-row space-y-2 md:space-y-0">
        <div className="flex-1">
          <Link className="btn btn-ghost normal-case text-xl" to="/">
            <img className="h-4 md:h-6" alt="Solana Logo" src="/assets/solana-logo.png" />
          </Link>
          <ul className="menu menu-horizontal px-1 space-x-2">
            {links.map(({ label, path }) => (
              <li key={path}>
                <Link className={pathname.startsWith(path) ? 'active' : ''} to={path}>
                  {label}
                </Link>
              </li>
            ))}
          </ul>
        </div>
        <div className="flex-none space-x-2">
          <WalletButton />
          <ClusterUiSelect />
        </div>
      </div>
      <ClusterChecker>
        <AccountChecker />
      </ClusterChecker>
      <div className="flex-grow mx-4 lg:mx-auto">
        <Suspense
          fallback={
            <div className="text-center my-32">
              <span className="loading loading-spinner loading-lg"></span>
            </div>
          }
        >
          {children}
        </Suspense>
        <Toaster position="bottom-right" />
      </div>
      <footer className="footer footer-center p-4 bg-base-300 text-base-content">
        <aside>
          <p>
            Generated by{' '}
            <a
              className="link hover:text-white"
              href="https://github.com/solana-developers/create-solana-dapp"
              target="_blank"
              rel="noopener noreferrer"
            >
              create-solana-dapp
            </a>
          </p>
        </aside>
      </footer>
    </div>
  )
}

export function AppModal({
  children,
  title,
  hide,
  show,
  submit,
  submitDisabled,
  submitLabel,
}: {
  children: ReactNode
  title: string
  hide: () => void
  show: boolean
  submit?: () => void
  submitDisabled?: boolean
  submitLabel?: string
}) {
  const dialogRef = useRef<HTMLDialogElement | null>(null)

  useEffect(() => {
    if (!dialogRef.current) return
    if (show) {
      dialogRef.current.showModal()
    } else {
      dialogRef.current.close()
    }
  }, [show, dialogRef])

  return (
    <dialog className="modal" ref={dialogRef}>
      <div className="modal-box space-y-5">
        <h3 className="font-bold text-lg">{title}</h3>
        {children}
        <div className="modal-action">
          <div className="join space-x-2">
            {submit ? (
              <button className="btn btn-xs lg:btn-md btn-primary" onClick={submit} disabled={submitDisabled}>
                {submitLabel || 'Save'}
              </button>
            ) : null}
            <button onClick={hide} className="btn">
              Close
            </button>
          </div>
        </div>
      </div>
    </dialog>
  )
}

export function AppHero({
  children,
  title,
  subtitle,
}: {
  children?: ReactNode
  title: ReactNode
  subtitle: ReactNode
}) {
  return (
    <div className="hero py-[64px]">
      <div className="hero-content text-center">
        <div className="max-w-2xl">
          {typeof title === 'string' ? <h1 className="text-5xl font-bold">{title}</h1> : title}
          {typeof subtitle === 'string' ? <p className="py-6">{subtitle}</p> : subtitle}
          {children}
        </div>
      </div>
    </div>
  )
}

export function ellipsify(str = '', len = 4) {
  if (str.length > 30) {
    return str.substring(0, len) + '..' + str.substring(str.length - len, str.length)
  }
  return str
}

export function useTransactionToast() {
  return (signature: string) => {
    toast.success(
      <div className={'text-center'}>
        <div className="text-lg">Transaction sent</div>
        <ExplorerLink path={`tx/${signature}`} label={'View Transaction'} className="btn btn-xs btn-primary" />
      </div>,
    )
  }
}
